### PR TITLE
More thorough hash removal

### LINKED ISSUE #31: HTML pages added to cache via manifest attribute still contain the hash fragment of the href
Work was done in #17 to remove hash part of URL from request URL and client URL but this same hash removal isn't being done for HTML pages added to the cache via the [`manifest`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/html/manifest) attribute.

e.g. 

https://github.com/GoogleChromeLabs/sw-appcache-behavior/blob/f7dc78d4a26a8b83640e418a8936130eacb0d69f/packages/appcache-polyfill-window/index.ts#L202-L214

There are likely other places that need to be updated too (e.g. in the service worker fetch).

This causes apps that load from the network with a hash fragment to not being able to retrieved from cache due to mismatching key. My team is attempting to work around this for now by changing our root URL to not have a hash fragment but this may not work in other applications or long term for my team. Thanks!

### PR DESCRIPTION
**Pull request by jeffposnick**
Please let me know if this is what you had in mind, @mfulton26.

Also CC: @arneschuldt who implemented a related change in this library previously.

Fixes #31

### CODE REVIEW

**Review by mfulton26 — APPROVED** [review]
yes, that looks right to me; what do you think @kirill578? thank you @jeffposnick

**Comment by arneschuldt** [comment]
Thank you very much @mfulton26 for reporting issue #31 which I obviously did not notice when providing pull request #17.

Thank you very much @jeffposnick for this improvement!

**Comment by mfulton26** [comment]
#17 was a good improvement; I'm glad you found that one too. It caused our app to not work offline for a bit because our app loading with a hash initially so it didn't get cached properly but we were able to remove the hash for the initial load as a workaround and I think with this fix that won't be necessary anymore. Teamwork! 😄

**Review by kirill578 — APPROVED** [review]

**Comment by jeffposnick** [comment]
https://github.com/GoogleChromeLabs/sw-appcache-behavior/releases/tag/v0.4.0

**Pull request merged**
